FROM php:8.5.9-fpm-alpine

RUN apk add --no-cache \
        git \
        unzip \
        icu-dev \
        libpq-dev \
        libzip-dev \
        oniguruma-dev \
    && docker-php-ext-install \
        intl \
        mbstring \
        pdo_pgsql \
        zip
        
RUN apk add --no-cache --virtual .redis-build-deps $PHPIZE_DEPS \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del .redis-build-deps

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

RUN git config --global --add safe.directory /var/www/html

WORKDIR /var/www/html/

CMD ["php-fpm"]