FROM php:8.5.9-fpm-alpine

RUN apk add --no-cache \
        git \
        unzip \
        icu-dev \
        libpq-dev \
        libzip-dev \
        oniguruma-dev \
    && docker-php-ext-install \
        intl \
        mbstring \
        pdo_pgsql \
        zip
        
RUN apk add --no-cache --virtual .redis-build-deps $PHPIZE_DEPS \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apk del .redis-build-deps

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

COPY docker/php/entrypoint.dev.sh /usr/local/bin/php-entrypoint-dev

RUN chmod +x /usr/local/bin/php-entrypoint-dev

WORKDIR /var/www/html/

ENTRYPOINT ["php-entrypoint-dev"]
CMD ["php-fpm"]